# Generated by Django 4.1.7 on 2023-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание задачи'),
        ),
    ]
