from os import getenv
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY: str = getenv('SECRET_KEY')
ALGORITHM: str = getenv('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 5
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 60
AWS_ACCESS_KEY_ID = getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = getenv('AWS_SECRET_ACCESS_KEY')
REGION_NAME = getenv('REGION_NAME')
BUCKET_NAME = getenv('BUCKET_NAME')

POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_PASSWORD = getenv('POSTGRES_PASSWORD')
POSTGRES_DB = getenv('POSTGRES_DB')
POSTGRES_HOST = getenv('POSTGRES_HOST')
